export enum CharacterSpecEnum {
  Arms = 'Arms',
  Fury = 'Fury',
  Protection = 'Protection',
  Holy = 'Holy',
  Retribution = 'Retribution',
  BeastMastery = 'BeastMastery',
  Marksmanship = 'Marksmanship',
  Survival = 'Survival',
  Balance = 'Balance',
  Feral = 'Feral',
  Restoration = 'Restoration',
  Assassination = 'Assassination',
  Combat = 'Combat',
  Subtlety = 'Subtlety',
  Affliction = 'Affliction',
  Demonology = 'Demonology',
  Destruction = 'Destruction',
  Arcane = 'Arcane',
  Fire = 'Fire',
  Frost = 'Frost',
  Discipline = 'Discipline',
  Shadow = 'Shadow',
  Elemental = 'Elemental',
  Enhancement = 'Enhancement',
}
