import dotenv from 'dotenv';
import { mkdirSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { WclStatsApiClient } from './api';
import { getAccessToken } from './auth';
import { bakeRaid } from './baker';
import { RAIDS, RANK_TARGETS, TRACKED_GUILDS } from './config';
import type { WclStatsData } from './types';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(scriptDir, '..', '..');
const outputPath = join(repoRoot, 'src', 'app', '_data', 'wcl-stats.data.ts');

export function validateBakedData(data: WclStatsData): void {
  if (data.raids.length !== RAIDS.length) throw new Error('Baked data does not contain every configured raid');
  for (const raid of data.raids) {
    for (const target of RANK_TARGETS) {
      if (!raid.rows.some(row => row.rank === target)) throw new Error(`${raid.name}: missing required rank ${target}`);
    }
    for (const guild of TRACKED_GUILDS) {
      if (!raid.rows.some(row => row.guildName === guild.name && row.guildGroup === guild.group)) {
        throw new Error(`${raid.name}: missing configured ${guild.group.toUpperCase()} guild ${guild.name}`);
      }
    }
  }
}

export function serializeBakedData(data: WclStatsData): string {
  return `// AUTO-GENERATED by npm run bake:wcl-stats. Do not edit manually.\n\n`
    + `export interface WclStatsRow {\n  rank: number | null;\n  guildName: string;\n  displayName: string;\n  faction?: 'Alliance' | 'Horde' | null;\n  region: string;\n  realm: string;\n  durationMs: number | null;\n  guildUrl: string;\n  reportUrl: string | null;\n  guildGroup: 'milestone' | 'ua' | 'ru';\n}\n\n`
    + `export interface WclStatsRaid {\n  id: 'ssc' | 'tk';\n  name: string;\n  encounterId: number;\n  rows: WclStatsRow[];\n}\n\n`
    + `export interface WclStatsData { generatedAt: string; raids: WclStatsRaid[]; }\n\n`
    + `export const wclStatsData: WclStatsData = ${JSON.stringify(data, null, 2)};\n`;
}

export function writeBakedData(data: WclStatsData, destination = outputPath): void {
  validateBakedData(data);
  mkdirSync(dirname(destination), { recursive: true });
  const temporaryPath = `${destination}.tmp`;
  writeFileSync(temporaryPath, serializeBakedData(data), 'utf8');
  renameSync(temporaryPath, destination);
}

async function main(): Promise<void> {
  dotenv.config({ path: join(repoRoot, '.env') });
  const clientId = process.env['WCL_CLIENT_ID'];
  const clientSecret = process.env['WCL_CLIENT_SECRET'];
  if (!clientId || !clientSecret) throw new Error('Missing WCL_CLIENT_ID or WCL_CLIENT_SECRET in the environment or .env');

  const api = new WclStatsApiClient(await getAccessToken(clientId, clientSecret));
  const raids = [];
  for (const raid of RAIDS) {
    console.log(`[wcl-stats-baker] Fetching ${raid.name}`);
    raids.push(await bakeRaid(api, raid));
  }
  const data: WclStatsData = { generatedAt: new Date().toISOString(), raids };
  writeBakedData(data);
  console.log(`[wcl-stats-baker] Wrote ${outputPath}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch(error => {
    console.error(`[wcl-stats-baker] ERROR: ${(error as Error).message}`);
    process.exitCode = 1;
  });
}
