import { CharacterRank } from '../_entities/character-rank.enum';
import { Player } from '../_entities/player';
import { CharacterRole } from '../_entities/character-role.enum';
import { CharacterClass } from '../_entities/character-class.enum';
import { CharacterSpecEnum } from '../_entities/character-spec.enum';

export const players: Player[] = [
  {
    name: 'Lazykit',
    discord: { userId: '298460716904611840' },
    characters: [
      {
        name: 'Lazykit',
        rank: CharacterRank.main,
        role: CharacterRole.melee,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Enhancement,
      },
      {
        name: 'Notalazy',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Retribution,
      },
      {
        name: 'Moneylazy',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.rogue,
        spec: CharacterSpecEnum.Combat,
      },
      {
        name: 'Lazykitstop',
        rank: CharacterRank.alt,
        role: CharacterRole.tank,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Feral,
      },
    ],
  },
  {
    name: 'Palayoshka',
    discord: { userId: '193687671359406080' },
    characters: [
      {
        name: 'Palayoshka',
        rank: CharacterRank.main,
        role: CharacterRole.healer,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Holy,
      },
      {
        name: 'Yoshkap',
        rank: CharacterRank.alt,
        role: CharacterRole.healer,
        class: CharacterClass.priest,
        spec: CharacterSpecEnum.Holy,
      },
    ],
  },
  {
    name: 'Krava',
    discord: { userId: '341841825847574528' },
    characters: [
      {
        name: 'Kravá',
        rank: CharacterRank.main,
        role: CharacterRole.tank,
        class: CharacterClass.warrior,
        spec: CharacterSpecEnum.Protection,
      },
      {
        name: 'Kravä',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.hunter,
        spec: CharacterSpecEnum.BeastMastery,
      },
      {
        name: 'Kravarlocka',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.warlock,
        spec: CharacterSpecEnum.Destruction,
      },
      {
        name: 'Kravashamanb',
        rank: CharacterRank.alt,
        role: CharacterRole.healer,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Restoration,
      },
      {
        name: 'Kravapalc',
        rank: CharacterRank.alt,
        role: CharacterRole.tank,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Protection,
      },
    ],
  },
  {
    name: 'Cambells',
    discord: { userId: '307413040712777730' },
    characters: [
      {
        name: 'Cambels',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.mage,
        spec: CharacterSpecEnum.Arcane,
      },
      {
        name: 'Cambellsh',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.hunter,
        spec: CharacterSpecEnum.Survival,
      },
      {
        name: 'Cambellsw',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.warrior,
        spec: CharacterSpecEnum.Fury,
      },
      {
        name: 'Heymanatomb',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.rogue,
        spec: CharacterSpecEnum.Combat,
      },
    ],
  },
  {
    name: 'Bawowna',
    discord: { userId: '230324826747699200' },
    characters: [
      {
        name: 'Bawownahunt',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.hunter,
        spec: CharacterSpecEnum.BeastMastery,
      },
      {
        name: 'Fleabus',
        rank: CharacterRank.alt,
        role: CharacterRole.healer,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Restoration,
      },
    ],
  },
  // {
  //   name: 'Dubasaw',
  //   discord: { userId: '526101639002587178' },
  //   characters: [
  //     {
  //       name: 'Dubasaw',
  //       rank: CharacterRank.main,
  //       role: CharacterRole.ranged,
  //       class: CharacterClass.hunter,
  //       spec: CharacterSpecEnum.BeastMastery,
  //     },
  //     {
  //       name: 'Dubasw',
  //       rank: CharacterRank.alt,
  //       role: CharacterRole.melee,
  //       class: CharacterClass.shaman,
  //       spec: CharacterSpecEnum.Enhancement,
  //     },
  //   ],
  // },
  // {
  //   name: 'Lansena',
  //   discord: { userId: '360123145522249729' },
  //   characters: [
  //     {
  //       name: 'Lansena',
  //       rank: CharacterRank.main,
  //       role: CharacterRole.healer,
  //       class: CharacterClass.priest,
  //       spec: CharacterSpecEnum.Holy,
  //     },
  //     {
  //       name: 'Mellorin',
  //       rank: CharacterRank.alt,
  //       role: CharacterRole.ranged,
  //       class: CharacterClass.druid,
  //       spec: CharacterSpecEnum.Balance,
  //     },
  //   ],
  // },
  // {
  //   name: 'Edgelord',
  //   discord: { userId: '257947077324177411' },
  //   characters: [
  //     {
  //       name: 'Edgelørd',
  //       rank: CharacterRank.main,
  //       role: CharacterRole.ranged,
  //       class: CharacterClass.warlock,
  //       spec: CharacterSpecEnum.Destruction,
  //     },
  //     {
  //       name: 'Udy',
  //       rank: CharacterRank.alt,
  //       role: CharacterRole.ranged,
  //       class: CharacterClass.priest,
  //       spec: CharacterSpecEnum.Shadow,
  //     },
  //   ],
  // },
  // {
  //   name: 'Brokentoy',
  //   discord: { userId: '234388219020443648' },
  //   characters: [
  //     {
  //       name: 'Brokentoy',
  //       rank: CharacterRank.main,
  //       role: CharacterRole.melee,
  //       class: CharacterClass.shaman,
  //       spec: CharacterSpecEnum.Enhancement,
  //     },
  //     {
  //       name: 'Zabyjaka',
  //       rank: CharacterRank.alt,
  //       role: CharacterRole.ranged,
  //       class: CharacterClass.shaman,
  //       spec: CharacterSpecEnum.Elemental,
  //     },
  //   ],
  // },
  {
    name: 'Entim',
    discord: { userId: '486541449568059402' },
    characters: [
      {
        name: 'Entim',
        rank: CharacterRank.main,
        role: CharacterRole.healer,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Restoration,
      },
      {
        name: 'Entimx',
        rank: CharacterRank.alt,
        role: CharacterRole.healer,
        class: CharacterClass.priest,
        spec: CharacterSpecEnum.Discipline,
      },
    ],
  },
  {
    name: 'Serjio',
    discord: { userId: '1322931563406688346' },
    characters: [
      {
        name: 'Serjioo',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.hunter,
        spec: CharacterSpecEnum.Survival,
      },
      {
        name: 'Serjoo',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.warrior,
        spec: CharacterSpecEnum.Arms,
      },
      {
        name: 'Serjo',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Balance,
      },
    ],
  },
  {
    name: 'Chaiser',
    discord: { userId: '353863554585067532' },
    characters: [
      {
        name: 'Chaiser',
        rank: CharacterRank.main,
        role: CharacterRole.tank,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Feral,
      },
      {
        name: 'Globaldoctor',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Enhancement,
      },
      {
        name: 'Altezzå',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.rogue,
        spec: CharacterSpecEnum.Combat,
      },
    ],
  },
  {
    name: 'Taurhorn',
    discord: { userId: '281040155429568512' },
    characters: [
      {
        name: 'Taurhorn',
        rank: CharacterRank.main,
        role: CharacterRole.tank,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Feral,
      },
    ],
  },
  {
    name: 'Xamyc',
    discord: { userId: '237142360595759104' },
    characters: [
      {
        name: 'Xamyc',
        rank: CharacterRank.main,
        role: CharacterRole.healer,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Restoration,
      },
      {
        name: 'Morfoza',
        rank: CharacterRank.alt,
        role: CharacterRole.healer,
        class: CharacterClass.priest,
        spec: CharacterSpecEnum.Holy,
      },
    ],
  },
  {
    name: 'Ersiliya',
    discord: { userId: '212531792220127232' },
    characters: [
      {
        name: 'Ersiliya',
        rank: CharacterRank.main,
        role: CharacterRole.healer,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Restoration,
      },
      {
        name: 'Lifehard',
        rank: CharacterRank.alt,
        role: CharacterRole.healer,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Holy,
      },
    ],
  },
  {
    name: 'Sayfer',
    discord: { userId: '234249857085210625' },
    characters: [
      {
        name: 'Sayfer',
        rank: CharacterRank.main,
        role: CharacterRole.healer,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Holy,
      },
      {
        name: 'Frenzyrage',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.warrior,
        spec: CharacterSpecEnum.Fury,
      },
    ],
  },
  {
    name: 'Legalise',
    discord: { userId: '364448191724257280' },
    characters: [
      {
        name: 'Legalise',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.hunter,
        spec: CharacterSpecEnum.BeastMastery,
      },
      {
        name: 'Tenten',
        rank: CharacterRank.alt,
        role: CharacterRole.tank,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Feral,
      },
      {
        name: 'Alpine',
        rank: CharacterRank.alt,
        role: CharacterRole.tank,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Protection,
      },
      {
        name: 'Livingstone',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.mage,
        spec: CharacterSpecEnum.Arcane,
      },
      {
        name: 'Yesterday',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.warrior,
        spec: CharacterSpecEnum.Arms,
      },
      {
        name: 'Kokochoco',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Enhancement,
      },
    ],
  },
  {
    name: 'Dontmissbyte',
    discord: { userId: '287674226440142848' },
    characters: [
      {
        name: 'Dontmissbyte',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Elemental,
      },
      {
        name: 'Kyivstar',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.warlock,
        spec: CharacterSpecEnum.Affliction,
      },
    ],
  },
  {
    name: 'Strike',
    discord: { userId: '235195687996882954' },
    characters: [
      {
        name: 'Hellpapa',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.warlock,
        spec: CharacterSpecEnum.Destruction,
      },
      {
        name: 'Strikex',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.rogue,
        spec: CharacterSpecEnum.Combat,
      },
    ],
  },
  {
    name: 'Swotch',
    discord: { userId: '226071331697852416' },
    characters: [
      {
        name: 'Swotchw',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.warlock,
        spec: CharacterSpecEnum.Destruction,
      },
      {
        name: 'Swotchww',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.warrior,
        spec: CharacterSpecEnum.Arms,
      },
      {
        name: 'Lazyswotch',
        rank: CharacterRank.alt,
        role: CharacterRole.healer,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Restoration,
      },
      {
        name: 'Alcoswotch',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Enhancement,
      },
    ],
  },
  {
    name: 'Lloydaustin',
    discord: { userId: '625411819334270976' },
    characters: [
      {
        name: 'Llóydaustin',
        rank: CharacterRank.main,
        role: CharacterRole.melee,
        class: CharacterClass.warrior,
        spec: CharacterSpecEnum.Fury,
      },
      {
        name: 'Pigtasty',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.hunter,
        spec: CharacterSpecEnum.BeastMastery,
      },
      {
        name: 'Shamkira',
        rank: CharacterRank.alt,
        role: CharacterRole.healer,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Restoration,
      },
      {
        name: 'Kegbear',
        rank: CharacterRank.alt,
        role: CharacterRole.tank,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Feral,
      },
      // {
      //   name: 'Lloydflurry',
      //   rank: CharacterRank.alt,
      //   role: CharacterRole.melee,
      //   class: CharacterClass.rogue,
      //   spec: CharacterSpecEnum.Combat,
      // },
    ],
  },
  {
    name: 'Zulnani',
    discord: { userId: '521657297693573120' },
    characters: [
      {
        name: 'Natatus',
        rank: CharacterRank.main,
        role: CharacterRole.tank,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Feral,
      },
      {
        name: 'Garhard',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.warlock,
        spec: CharacterSpecEnum.Destruction,
      },
      {
        name: 'Nahába',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.warrior,
        spec: CharacterSpecEnum.Fury,
      },
    ],
  },
  // {
  //   name: 'Amorales',
  //   discord: { userId: '556582468002775050' },
  //   characters: [
  //     {
  //       name: 'Bozer',
  //       rank: CharacterRank.main,
  //       role: CharacterRole.melee,
  //       class: CharacterClass.warrior,
  //       spec: CharacterSpecEnum.Arms,
  //     },
  //     {
  //       name: 'Amorales',
  //       rank: CharacterRank.alt,
  //       role: CharacterRole.ranged,
  //       class: CharacterClass.warlock,
  //       spec: CharacterSpecEnum.Destruction,
  //     },
  //   ],
  // },
  {
    name: 'Roombaboomba',
    discord: { userId: '556582468002775050' },
    characters: [
      {
        name: 'Serlo',
        rank: CharacterRank.main,
        role: CharacterRole.melee,
        class: CharacterClass.warrior,
        spec: CharacterSpecEnum.Arms,
      },
      {
        name: 'Roombaboomba',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.warlock,
        spec: CharacterSpecEnum.Affliction,
      },
      {
        name: 'Moorkit',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Balance,
      },
      {
        name: 'Wolfgangster',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Enhancement,
      },
      {
        name: 'Bdzhilka',
        rank: CharacterRank.alt,
        role: CharacterRole.tank,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Protection,
      },
    ],
  },
  {
    name: 'Renko',
    discord: { userId: '319831527821410316' },
    characters: [
      {
        name: 'Renko',
        rank: CharacterRank.main,
        role: CharacterRole.melee,
        class: CharacterClass.rogue,
        spec: CharacterSpecEnum.Combat,
      },
      {
        name: 'Anyataylorj',
        rank: CharacterRank.alt,
        role: CharacterRole.tank,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Feral,
      },
      {
        name: 'Fantagodx',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.mage,
        spec: CharacterSpecEnum.Arcane,
      },
      {
        name: 'Tonyafuria',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.hunter,
        spec: CharacterSpecEnum.BeastMastery,
      },
      {
        name: 'Tonyflurry',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.warrior,
        spec: CharacterSpecEnum.Fury,
      },
    ],
  },
  {
    name: 'Pappit',
    discord: { userId: '580756767148081152' },
    characters: [
      {
        name: 'Pappit',
        rank: CharacterRank.main,
        role: CharacterRole.melee,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Retribution,
      },
      {
        name: 'Puppit',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Enhancement,
      },
    ],
  },
  {
    name: 'Retributia',
    discord: { userId: '580756767148081152' },
    characters: [
      {
        name: 'Retributia',
        rank: CharacterRank.main,
        role: CharacterRole.melee,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Retribution,
      },
      {
        name: 'Retrivutia',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Retribution,
      },
    ],
  },
  {
    name: 'Thundermate',
    discord: { userId: '247320467310903297' },
    characters: [
      {
        name: 'Thundermate',
        rank: CharacterRank.main,
        role: CharacterRole.melee,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Enhancement,
      },
      {
        name: 'Blinkmate',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.mage,
        spec: CharacterSpecEnum.Arcane,
      },
    ],
  },
  {
    name: 'Rinn',
    discord: { userId: '244543163702837259' },
    characters: [
      {
        name: 'Rinn',
        rank: CharacterRank.main,
        role: CharacterRole.tank,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Protection,
      },
      {
        name: 'Figurehead',
        rank: CharacterRank.alt,
        role: CharacterRole.healer,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Restoration,
      },
      {
        name: 'Rinrogue',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.rogue,
        spec: CharacterSpecEnum.Combat,
      },
    ],
  },
  {
    name: 'Chortenya',
    discord: { userId: '163288553923543041' },
    characters: [
      {
        name: 'Chortenya',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.warlock,
        spec: CharacterSpecEnum.Destruction,
      },
      {
        name: 'Sypukha',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Balance,
      },
    ],
  },
  {
    name: 'Ryzha',
    discord: { userId: '128246284447514624' },
    characters: [
      {
        name: 'Ryzhã',
        rank: CharacterRank.main,
        role: CharacterRole.healer,
        class: CharacterClass.priest,
        spec: CharacterSpecEnum.Holy,
      },
      {
        name: 'Ryzha',
        rank: CharacterRank.alt,
        role: CharacterRole.healer,
        class: CharacterClass.priest,
        spec: CharacterSpecEnum.Holy,
      },
      {
        name: 'Flamingô',
        rank: CharacterRank.alt,
        role: CharacterRole.healer,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Restoration,
      },
    ],
  },
  {
    name: 'Alarian',
    discord: { userId: '532245370944880640' },
    characters: [
      {
        name: 'Alarian',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.priest,
        spec: CharacterSpecEnum.Shadow,
      },
      {
        name: 'Elitemob',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Enhancement,
      },
      {
        name: 'Hatus',
        rank: CharacterRank.alt,
        role: CharacterRole.healer,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Holy,
      },
    ],
  },
  {
    name: 'Dixonmyez',
    discord: { userId: '598212398125416468' },
    characters: [
      {
        name: 'Dixonmyez',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.priest,
        spec: CharacterSpecEnum.Shadow,
      },
      {
        name: 'Dixonmyezpala',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Retribution,
      },
    ],
  },
  {
    name: 'Oxi',
    discord: { userId: '1012404881656647720' },
    characters: [
      {
        name: 'Northsidewet',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.priest,
        spec: CharacterSpecEnum.Shadow,
      },
      // {
      //   name: 'Northsideopm',
      //   rank: CharacterRank.alt,
      //   role: CharacterRole.ranged,
      //   class: CharacterClass.mage,
      //   spec: CharacterSpecEnum.Arcane,
      // },
      // {
      //   name: 'Icausepanic',
      //   rank: CharacterRank.alt,
      //   role: CharacterRole.ranged,
      //   class: CharacterClass.hunter,
      //   spec: CharacterSpecEnum.BeastMastery,
      // },
    ],
  },
  {
    name: 'Sustainable',
    discord: { userId: '379260041066446849' },
    characters: [
      {
        name: 'Betonnyi',
        rank: CharacterRank.main,
        role: CharacterRole.melee,
        class: CharacterClass.warrior,
        spec: CharacterSpecEnum.Arms,
      },
    ],
  },
  {
    name: 'Manowarr',
    discord: { userId: '283222297807028224' },
    characters: [
      {
        name: 'Manowarr',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.hunter,
        spec: CharacterSpecEnum.BeastMastery,
      },
      {
        name: 'Månowar',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.hunter,
        spec: CharacterSpecEnum.BeastMastery,
      },
    ],
  },
  {
    name: 'Professor',
    discord: { userId: '1002921317051420703' },
    characters: [
      {
        name: 'Prõfessõr',
        rank: CharacterRank.main,
        role: CharacterRole.tank,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Protection,
      },
      {
        name: 'Prõfessõrr',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.warlock,
        spec: CharacterSpecEnum.Affliction,
      },
    ],
  },
  {
    name: 'Benzobak',
    discord: { userId: '817226698071998484' },
    characters: [
      {
        name: 'Benzöbak',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Balance,
      },
      {
        name: 'Möxentöxen',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.warlock,
        spec: CharacterSpecEnum.Affliction,
      },
    ],
  },
  {
    name: 'Fline',
    discord: { userId: '431791718535528448' },
    characters: [
      {
        name: 'Flinesham',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Elemental,
      },
      {
        name: 'Skifon',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.mage,
        spec: CharacterSpecEnum.Arcane,
      },
    ],
  },
  {
    name: 'Nevercome',
    discord: { userId: '252177261006946304' },
    characters: [
      {
        name: 'Monkablaze',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.mage,
        spec: CharacterSpecEnum.Arcane,
      },
      {
        name: 'Monkablazé',
        rank: CharacterRank.alt,
        role: CharacterRole.tank,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Protection,
      }
    ],
  },
  {
    name: 'Deserve',
    discord: { userId: '961651735187841114' },
    characters: [
      {
        name: 'Deserve',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.hunter,
        spec: CharacterSpecEnum.BeastMastery,
      },
      {
        name: 'Deserv',
        rank: CharacterRank.alt,
        role: CharacterRole.tank,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Feral,
      },
      {
        name: 'Deserving',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.priest,
        spec: CharacterSpecEnum.Shadow,
      },
    ],
  },
  {
    name: 'Obivan',
    discord: { userId: '305053799523942401' },
    characters: [
      {
        name: 'Obivankapman',
        rank: CharacterRank.main,
        role: CharacterRole.melee,
        class: CharacterClass.rogue,
        spec: CharacterSpecEnum.Combat,
      },
      {
        name: 'Yourßunywrot',
        rank: CharacterRank.alt,
        role: CharacterRole.ranged,
        class: CharacterClass.priest,
        spec: CharacterSpecEnum.Shadow,
      },
    ],
  },
  {
    name: 'Joyboyx',
    discord: { userId: '320898119082573824' },
    characters: [
      {
        name: 'Joyboyx',
        rank: CharacterRank.main,
        role: CharacterRole.melee,
        class: CharacterClass.paladin,
        spec: CharacterSpecEnum.Retribution,
      },
      {
        name: 'Hromovyk',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Enhancement,
      },
    ],
  },
  {
    name: 'Grobash',
    discord: { userId: '839586121754476545' },
    characters: [
      {
        name: 'Haìlrake',
        rank: CharacterRank.main,
        role: CharacterRole.melee,
        class: CharacterClass.shaman,
        spec: CharacterSpecEnum.Enhancement,
      },
      {
        name: 'Grobash',
        rank: CharacterRank.alt,
        role: CharacterRole.melee,
        class: CharacterClass.warrior,
        spec: CharacterSpecEnum.Arms,
      },
    ],
  },
  {
    name: 'Dieforyou',
    discord: { userId: '260805426340298754' },
    characters: [
      {
        name: 'Dieforyou',
        rank: CharacterRank.main,
        role: CharacterRole.healer,
        class: CharacterClass.priest,
        spec: CharacterSpecEnum.Holy,
      },
    ],
  },
  {
    name: 'Minerv',
    discord: { userId: '' },
    characters: [
      {
        name: 'Gösling',
        rank: CharacterRank.main,
        role: CharacterRole.ranged,
        class: CharacterClass.mage,
        spec: CharacterSpecEnum.Arcane,
      },
    ],
  },
  {
    name: 'Shudo',
    discord: { userId: '' },
    characters: [
      {
        name: 'Shudonyancat',
        rank: CharacterRank.main,
        role: CharacterRole.tank,
        class: CharacterClass.druid,
        spec: CharacterSpecEnum.Feral,
      },
    ],
  },
];
