// AUTO-GENERATED by npm run bake:wcl-stats. Do not edit manually.

export interface WclStatsRow {
  rank: number | null;
  guildName: string;
  displayName: string;
  faction?: 'Alliance' | 'Horde' | null;
  region: string;
  realm: string;
  durationMs: number | null;
  guildUrl: string;
  reportUrl: string | null;
  guildGroup: 'milestone' | 'ua' | 'ru';
}

export interface WclStatsRaid {
  id: 'bt' | 'hyjal';
  name: string;
  encounterId: number;
  rows: WclStatsRow[];
}

export interface WclStatsData { generatedAt: string; raids: WclStatsRaid[]; }

export const wclStatsData: WclStatsData = {
  "generatedAt": "2026-09-02T21:21:08.464Z",
  "raids": [
    {
      "id": "bt",
      "name": "Black Temple",
      "encounterId": 50704,
      "rows": [
        {
          "rank": 1,
          "guildName": "DPS CLUB",
          "displayName": "DPS CLUB",
          "faction": null,
          "region": "eu",
          "realm": "Thunderstrike",
          "durationMs": 4429778,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/thunderstrike/dps%20club",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/nA2G86x9BZqTpHyf",
          "guildGroup": "milestone"
        },
        {
          "rank": 25,
          "guildName": "Very secret pug",
          "displayName": "Very secret pug",
          "faction": null,
          "region": "eu",
          "realm": "Thunderstrike",
          "durationMs": 6540192,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/thunderstrike/very%20secret%20pug",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/vb3N6PJXz1BhRcMG",
          "guildGroup": "milestone"
        },
        {
          "rank": 50,
          "guildName": "HUNKS",
          "displayName": "HUNKS",
          "faction": null,
          "region": "eu",
          "realm": "Nightslayer",
          "durationMs": 7351879,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/nightslayer/hunks",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/cBmXCphPkQj3tWbg",
          "guildGroup": "milestone"
        },
        {
          "rank": 100,
          "guildName": "Ïzhachok",
          "displayName": "Ïzhachok",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 8260165,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/%C3%AFzhachok",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/R4CzJPbyj91BFkYh",
          "guildGroup": "ua"
        },
        {
          "rank": 111,
          "guildName": "Just Ask",
          "displayName": "Just Ask",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 8458113,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/just%20ask",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/ntMYCRb3HrhkxyTV",
          "guildGroup": "ru"
        },
        {
          "rank": 120,
          "guildName": "CBITAHOK",
          "displayName": "CBITAHOK",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 8606388,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cbitahok",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/cDt1ZCj9RnQNBrdf",
          "guildGroup": "ua"
        },
        {
          "rank": 124,
          "guildName": "DELETED",
          "displayName": "DELETED",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 8651172,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/deleted",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/rJnzyHT76gWjtvLG",
          "guildGroup": "ru"
        },
        {
          "rank": 251,
          "guildName": "SWP in Three Days",
          "displayName": "SWP in Three Days",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 10442117,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/swp%20in%20three%20days",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/CV7QNKTnajJ6xB4L",
          "guildGroup": "ua"
        },
        {
          "rank": 376,
          "guildName": "BOARS",
          "displayName": "BOARS",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 12448502,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/boars",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/rx4hGRFd79cTzaHg",
          "guildGroup": "ru"
        },
        {
          "rank": 429,
          "guildName": "Unexpected Journey",
          "displayName": "Unexpected Journey",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 13056232,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/unexpected%20journey",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/Aywqc3fGm1rjxTPv",
          "guildGroup": "ru"
        },
        {
          "rank": 495,
          "guildName": "Dwarves drank Baikal",
          "displayName": "Dwarves drank Baikal",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 14414914,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/dwarves%20drank%20baikal",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/BqfVQ1gA9hPTv38L",
          "guildGroup": "ru"
        },
        {
          "rank": 581,
          "guildName": "Trade Goods",
          "displayName": "Trade Goods",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 16951651,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/trade%20goods",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/mdDba8Ynyvp6HG9V",
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "LiberalPug",
          "displayName": "LiberalPug",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/liberalpug",
          "reportUrl": null,
          "guildGroup": "ua"
        },
        {
          "rank": null,
          "guildName": "MokNatal UA",
          "displayName": "MokNatal UA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/moknatal%20ua",
          "reportUrl": null,
          "guildGroup": "ua"
        },
        {
          "rank": null,
          "guildName": "Ukrainian Ironbelly",
          "displayName": "Ukrainian Ironbelly",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/ukrainian%20ironbelly",
          "reportUrl": null,
          "guildGroup": "ua"
        },
        {
          "rank": null,
          "guildName": "Trident Reborn",
          "displayName": "Trident Reborn",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/trident%20reborn",
          "reportUrl": null,
          "guildGroup": "ua"
        },
        {
          "rank": null,
          "guildName": "BAPTA",
          "displayName": "BAPTA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/bapta",
          "reportUrl": null,
          "guildGroup": "ua"
        },
        {
          "rank": null,
          "guildName": "ATB",
          "displayName": "ATB",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/atb",
          "reportUrl": null,
          "guildGroup": "ua"
        },
        {
          "rank": null,
          "guildName": "CMEPEKA",
          "displayName": "CMEPEKA",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cmepeka",
          "reportUrl": null,
          "guildGroup": "ua"
        },
        {
          "rank": null,
          "guildName": "Annuit Coeptis",
          "displayName": "Annuit Coeptis",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/annuit%20coeptis",
          "reportUrl": null,
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "GAMBIT",
          "displayName": "GAMBIT",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/gambit",
          "reportUrl": null,
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "Its Official",
          "displayName": "Its Official",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/its%20official",
          "reportUrl": null,
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "N O R D",
          "displayName": "N O R D",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/n%20o%20r%20d",
          "reportUrl": null,
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "CEBEP POMNIT",
          "displayName": "CEBEP POMNIT",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cebep%20pomnit",
          "reportUrl": null,
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "Eternal Sleep",
          "displayName": "Eternal Sleep",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/eternal%20sleep",
          "reportUrl": null,
          "guildGroup": "ru"
        }
      ]
    },
    {
      "id": "hyjal",
      "name": "Hyjal Summit",
      "encounterId": 50705,
      "rows": [
        {
          "rank": 1,
          "guildName": "Spatha",
          "displayName": "Spatha",
          "faction": null,
          "region": "eu",
          "realm": "Spineshatter",
          "durationMs": 2694317,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/spatha",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/r2kPCx6ngTmcd9RN",
          "guildGroup": "milestone"
        },
        {
          "rank": 25,
          "guildName": "Consanguineus",
          "displayName": "Consanguineus",
          "faction": null,
          "region": "eu",
          "realm": "Thunderstrike",
          "durationMs": 3280568,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/thunderstrike/consanguineus",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/czjYCqw16tfNMpkD",
          "guildGroup": "milestone"
        },
        {
          "rank": 50,
          "guildName": "Next Topic Move On - SCHLONG",
          "displayName": "Next Topic Move On - SCHLONG",
          "faction": null,
          "region": "eu",
          "realm": "Dreamscythe",
          "durationMs": 3465864,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/dreamscythe/next%20topic%20move%20on%20-%20schlong",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/2yKV39XAFGcZQfMC",
          "guildGroup": "milestone"
        },
        {
          "rank": 100,
          "guildName": "Get Carried",
          "displayName": "Get Carried",
          "faction": null,
          "region": "eu",
          "realm": "Nightslayer",
          "durationMs": 3703881,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/nightslayer/get%20carried",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/Abpk9xLDQ2GTrya3",
          "guildGroup": "milestone"
        },
        {
          "rank": 115,
          "guildName": "DELETED",
          "displayName": "DELETED",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3767231,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/deleted",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/rJnzyHT76gWjtvLG",
          "guildGroup": "ru"
        },
        {
          "rank": 133,
          "guildName": "SWP in Three Days",
          "displayName": "SWP in Three Days",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3828253,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/swp%20in%20three%20days",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/gcqryL62pfFMxzbv",
          "guildGroup": "ua"
        },
        {
          "rank": 139,
          "guildName": "Just Ask",
          "displayName": "Just Ask",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3861350,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/just%20ask",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/BK98TAfGXcwg4Q6J",
          "guildGroup": "ru"
        },
        {
          "rank": 173,
          "guildName": "Trade Goods",
          "displayName": "Trade Goods",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4002539,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/trade%20goods",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/621Prt8kM3yZdWaQ",
          "guildGroup": "ru"
        },
        {
          "rank": 243,
          "guildName": "Ïzhachok",
          "displayName": "Ïzhachok",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4274798,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/%C3%AFzhachok",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/bTgWqF7VzGXJrMtD",
          "guildGroup": "ua"
        },
        {
          "rank": 273,
          "guildName": "Dwarves drank Baikal",
          "displayName": "Dwarves drank Baikal",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4371605,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/dwarves%20drank%20baikal",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/BqfVQ1gA9hPTv38L",
          "guildGroup": "ru"
        },
        {
          "rank": 329,
          "guildName": "CBITAHOK",
          "displayName": "CBITAHOK",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4502609,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cbitahok",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/cDt1ZCj9RnQNBrdf",
          "guildGroup": "ua"
        },
        {
          "rank": 852,
          "guildName": "Its Official",
          "displayName": "Its Official",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5805221,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/its%20official",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/NPkKzqAJ6Mx4HWG7",
          "guildGroup": "ru"
        },
        {
          "rank": 939,
          "guildName": "Unexpected Journey",
          "displayName": "Unexpected Journey",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5995361,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/unexpected%20journey",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/fdHyVnzgwGNQkJXT",
          "guildGroup": "ru"
        },
        {
          "rank": 1186,
          "guildName": "LiberalPug",
          "displayName": "LiberalPug",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 6610527,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/liberalpug",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/PrRDfzaZjF4McYh3",
          "guildGroup": "ua"
        },
        {
          "rank": 1557,
          "guildName": "CMEPEKA",
          "displayName": "CMEPEKA",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 7641502,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cmepeka",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/jCxYL2VBt3DJNPa1",
          "guildGroup": "ua"
        },
        {
          "rank": 1784,
          "guildName": "ATB",
          "displayName": "ATB",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 8275735,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/atb",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/CAgHZMWpR43ka7JG",
          "guildGroup": "ua"
        },
        {
          "rank": 2097,
          "guildName": "Ukrainian Ironbelly",
          "displayName": "Ukrainian Ironbelly",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 9440273,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/ukrainian%20ironbelly",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/rCGn6VRvxLFTtyq3",
          "guildGroup": "ua"
        },
        {
          "rank": 2243,
          "guildName": "MokNatal UA",
          "displayName": "MokNatal UA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 10010774,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/moknatal%20ua",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/btcvwMYKZP6Dngrx",
          "guildGroup": "ua"
        },
        {
          "rank": 2496,
          "guildName": "Trident Reborn",
          "displayName": "Trident Reborn",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 12567646,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/trident%20reborn",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/PBbXKctWf7TZgV1w",
          "guildGroup": "ua"
        },
        {
          "rank": null,
          "guildName": "BAPTA",
          "displayName": "BAPTA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/bapta",
          "reportUrl": null,
          "guildGroup": "ua"
        },
        {
          "rank": null,
          "guildName": "Annuit Coeptis",
          "displayName": "Annuit Coeptis",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/annuit%20coeptis",
          "reportUrl": null,
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "BOARS",
          "displayName": "BOARS",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/boars",
          "reportUrl": null,
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "GAMBIT",
          "displayName": "GAMBIT",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/gambit",
          "reportUrl": null,
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "N O R D",
          "displayName": "N O R D",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/n%20o%20r%20d",
          "reportUrl": null,
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "CEBEP POMNIT",
          "displayName": "CEBEP POMNIT",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cebep%20pomnit",
          "reportUrl": null,
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "Eternal Sleep",
          "displayName": "Eternal Sleep",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/eternal%20sleep",
          "reportUrl": null,
          "guildGroup": "ru"
        }
      ]
    }
  ]
};
