// AUTO-GENERATED by npm run bake:wcl-stats. Do not edit manually.

export interface WclStatsRow {
  rank: number | null;
  guildName: string;
  displayName: string;
  faction?: 'Alliance' | 'Horde' | null;
  region: string;
  realm: string;
  durationMs: number | null;
  guildUrl: string;
  reportUrl: string | null;
  guildGroup: 'milestone' | 'ua' | 'ru';
}

export interface WclStatsRaid {
  id: 'ssc' | 'tk';
  name: string;
  encounterId: number;
  rows: WclStatsRow[];
}

export interface WclStatsData { generatedAt: string; raids: WclStatsRaid[]; }

export const wclStatsData: WclStatsData = {
  "generatedAt": "2026-07-21T13:26:18.800Z",
  "raids": [
    {
      "id": "tk",
      "name": "Tempest Keep",
      "encounterId": 100703,
      "rows": [
        {
          "rank": 1,
          "guildName": "Eternal",
          "displayName": "Eternal",
          "faction": null,
          "region": "eu",
          "realm": "Nightslayer",
          "durationMs": 1565326,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/nightslayer/eternal",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/vpXFrjKwDcY2n7A3",
          "guildGroup": "milestone"
        },
        {
          "rank": 50,
          "guildName": "Altlasten",
          "displayName": "Altlasten",
          "faction": null,
          "region": "eu",
          "realm": "Thunderstrike",
          "durationMs": 2240818,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/thunderstrike/altlasten",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/28Y9hjbR4JwQPBFL",
          "guildGroup": "milestone"
        },
        {
          "rank": 89,
          "guildName": "Ïzhachok",
          "displayName": "Ïzhachok",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2513442,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/%C3%AFzhachok",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/FrkWDLYhNgmwMafy",
          "guildGroup": "ua"
        },
        {
          "rank": 96,
          "guildName": "CBITAHOK",
          "displayName": "CBITAHOK",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2545505,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cbitahok",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/6d39b2rKH4g8xGNQ",
          "guildGroup": "ua"
        },
        {
          "rank": 98,
          "guildName": "Just Ask",
          "displayName": "Just Ask",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2556870,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/just%20ask",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/pfgz6L3WFXZcPKvR",
          "guildGroup": "ru"
        },
        {
          "rank": 100,
          "guildName": "Lifted",
          "displayName": "Lifted",
          "faction": null,
          "region": "eu",
          "realm": "Nightslayer",
          "durationMs": 2568391,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/nightslayer/lifted",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/MNRdZknTvwr4aBFA",
          "guildGroup": "milestone"
        },
        {
          "rank": 209,
          "guildName": "BOARS",
          "displayName": "BOARS",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2883583,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/boars",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/raL7xYdbwnpZKkjq",
          "guildGroup": "ru"
        },
        {
          "rank": 223,
          "guildName": "DELETED",
          "displayName": "DELETED",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2900918,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/deleted",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/PdGzx43D6R29LWBt",
          "guildGroup": "ru"
        },
        {
          "rank": 260,
          "guildName": "Dwarves drank Baikal",
          "displayName": "Dwarves drank Baikal",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2967576,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/dwarves%20drank%20baikal",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/qBRcV2PhD4FQw8Ty",
          "guildGroup": "ru"
        },
        {
          "rank": 736,
          "guildName": "N O R D",
          "displayName": "N O R D",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3441239,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/n%20o%20r%20d",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/LkyMdaJ6hH7Cbt4W",
          "guildGroup": "ru"
        },
        {
          "rank": 845,
          "guildName": "Trade Goods",
          "displayName": "Trade Goods",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3514056,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/trade%20goods",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/j9JqVD3wRmnCkgtT",
          "guildGroup": "ru"
        },
        {
          "rank": 860,
          "guildName": "Unexpected Journey",
          "displayName": "Unexpected Journey",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3523177,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/unexpected%20journey",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/BLmtxVvk7wPzFrd3",
          "guildGroup": "ru"
        },
        {
          "rank": 1063,
          "guildName": "SWP in Three Days",
          "displayName": "SWP in Three Days",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3636166,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/swp%20in%20three%20days",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/FPQzN9xfC4c6hAG8",
          "guildGroup": "ua"
        },
        {
          "rank": 1087,
          "guildName": "Eternal Sleep",
          "displayName": "Eternal Sleep",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3648529,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/eternal%20sleep",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/Wpcwjdz3trNnMC6T",
          "guildGroup": "ru"
        },
        {
          "rank": 1132,
          "guildName": "Its Official",
          "displayName": "Its Official",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3666521,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/its%20official",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/P6mckBwtagAxbVLq",
          "guildGroup": "ru"
        },
        {
          "rank": 1259,
          "guildName": "GAMBIT",
          "displayName": "GAMBIT",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3725566,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/gambit",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/jzn1taC4JLkN9Z3K",
          "guildGroup": "ru"
        },
        {
          "rank": 1730,
          "guildName": "MATRëSHKA",
          "displayName": "MATRëSHKA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3918245,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/matr%C3%ABshka",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/7TGajDwV6zvgnxfc",
          "guildGroup": "ru"
        },
        {
          "rank": 2115,
          "guildName": "LiberalPug",
          "displayName": "LiberalPug",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4058712,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/liberalpug",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/ZzntxJCBrDayR8bg",
          "guildGroup": "ua"
        },
        {
          "rank": 2226,
          "guildName": "ATB",
          "displayName": "ATB",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4104524,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/atb",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/RQr1gdYLFqWHVnBJ",
          "guildGroup": "ua"
        },
        {
          "rank": 2239,
          "guildName": "MokNatal UA",
          "displayName": "MokNatal UA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4110372,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/moknatal%20ua",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/hqwbnTCKAXygkMJd",
          "guildGroup": "ua"
        },
        {
          "rank": 2770,
          "guildName": "Faceroll",
          "displayName": "Faceroll",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4341209,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/faceroll",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/LgVtjz8T4WhyqGmn",
          "guildGroup": "ru"
        },
        {
          "rank": 2875,
          "guildName": "MUGIWARA",
          "displayName": "MUGIWARA",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4405630,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/mugiwara",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/JTNrA2PcMRkLYj36",
          "guildGroup": "ru"
        },
        {
          "rank": 2927,
          "guildName": "Free Will",
          "displayName": "Free Will",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4434071,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/free%20will",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/ZAYBDMdfGXjW4L32",
          "guildGroup": "ru"
        },
        {
          "rank": 3084,
          "guildName": "Warsong",
          "displayName": "Warsong",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4514287,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/warsong",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/HD2FYmq83kPAagp6",
          "guildGroup": "ru"
        },
        {
          "rank": 3241,
          "guildName": "BAPTA",
          "displayName": "BAPTA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4593944,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/bapta",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/rQBtG4XpnLMTc8K3",
          "guildGroup": "ua"
        },
        {
          "rank": 3555,
          "guildName": "Ukrainian Ironbelly",
          "displayName": "Ukrainian Ironbelly",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4772495,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/ukrainian%20ironbelly",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/HL6F9GAPTXj7wM4m",
          "guildGroup": "ua"
        },
        {
          "rank": 3973,
          "guildName": "CMEPEKA",
          "displayName": "CMEPEKA",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5080346,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cmepeka",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/b1Gt4n8gaY9TXAxR",
          "guildGroup": "ua"
        },
        {
          "rank": 4705,
          "guildName": "Trident Reborn",
          "displayName": "Trident Reborn",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 6365911,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/trident%20reborn",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/qAYmLQbwM4GKZx9j",
          "guildGroup": "ua"
        },
        {
          "rank": 4705,
          "guildName": "CEBEP POMNIT",
          "displayName": "CEBEP POMNIT",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 11606605,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cebep%20pomnit",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/8dJPLYw36mFkHtrb",
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "Annuit Coeptis",
          "displayName": "Annuit Coeptis",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/annuit%20coeptis",
          "reportUrl": null,
          "guildGroup": "ru"
        }
      ]
    },
    {
      "id": "ssc",
      "name": "Serpentshrine Cavern",
      "encounterId": 100702,
      "rows": [
        {
          "rank": 1,
          "guildName": "Progress",
          "displayName": "Progress",
          "faction": null,
          "region": "eu",
          "realm": "Spineshatter",
          "durationMs": 1684508,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/progress",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/p6HrAjZMG1gYbV2J",
          "guildGroup": "milestone"
        },
        {
          "rank": 50,
          "guildName": "Magnum",
          "displayName": "Magnum",
          "faction": null,
          "region": "eu",
          "realm": "Nightslayer",
          "durationMs": 2358518,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/nightslayer/magnum",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/B7zQahZ986VqN2Dr",
          "guildGroup": "milestone"
        },
        {
          "rank": 74,
          "guildName": "Just Ask",
          "displayName": "Just Ask",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2554636,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/just%20ask",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/pfgz6L3WFXZcPKvR",
          "guildGroup": "ru"
        },
        {
          "rank": 87,
          "guildName": "CBITAHOK",
          "displayName": "CBITAHOK",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2661168,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cbitahok",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/7XF4TNfpdYywHCRz",
          "guildGroup": "ua"
        },
        {
          "rank": 100,
          "guildName": "Roots",
          "displayName": "Roots",
          "faction": null,
          "region": "eu",
          "realm": "Nightslayer",
          "durationMs": 2717464,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/nightslayer/roots",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/PhQb74GJvCwDkcd6",
          "guildGroup": "milestone"
        },
        {
          "rank": 149,
          "guildName": "Dwarves drank Baikal",
          "displayName": "Dwarves drank Baikal",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3058749,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/dwarves%20drank%20baikal",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/hXDGJkxCpWrdQK1Y",
          "guildGroup": "ru"
        },
        {
          "rank": 170,
          "guildName": "BOARS",
          "displayName": "BOARS",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3146415,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/boars",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/w9TaZgxDykfmJ6dN",
          "guildGroup": "ru"
        },
        {
          "rank": 199,
          "guildName": "Ïzhachok",
          "displayName": "Ïzhachok",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3252919,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/%C3%AFzhachok",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/tX6C9Yj7cdmVpkT1",
          "guildGroup": "ua"
        },
        {
          "rank": 219,
          "guildName": "DELETED",
          "displayName": "DELETED",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3308713,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/deleted",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/AGCzmPtaJXw6MRTK",
          "guildGroup": "ru"
        },
        {
          "rank": 397,
          "guildName": "N O R D",
          "displayName": "N O R D",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3654884,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/n%20o%20r%20d",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/z31gpbWZvtNy2RqJ",
          "guildGroup": "ru"
        },
        {
          "rank": 488,
          "guildName": "Unexpected Journey",
          "displayName": "Unexpected Journey",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3774512,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/unexpected%20journey",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/ZGkHtgnTdJKymN8r",
          "guildGroup": "ru"
        },
        {
          "rank": 562,
          "guildName": "SWP in Three Days",
          "displayName": "SWP in Three Days",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3851015,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/swp%20in%20three%20days",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/AY7GHgh4Fk8NvtD9",
          "guildGroup": "ua"
        },
        {
          "rank": 612,
          "guildName": "Trade Goods",
          "displayName": "Trade Goods",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3899692,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/trade%20goods",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/4PmDTBcnArygpCX7",
          "guildGroup": "ru"
        },
        {
          "rank": 1593,
          "guildName": "MATRëSHKA",
          "displayName": "MATRëSHKA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4583444,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/matr%C3%ABshka",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/wHcVPAm1xF7jRZTD",
          "guildGroup": "ru"
        },
        {
          "rank": 1688,
          "guildName": "Its Official",
          "displayName": "Its Official",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4632002,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/its%20official",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/P6mckBwtagAxbVLq",
          "guildGroup": "ru"
        },
        {
          "rank": 2171,
          "guildName": "LiberalPug",
          "displayName": "LiberalPug",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4884570,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/liberalpug",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/3yDHrQm4FzJKkhLP",
          "guildGroup": "ua"
        },
        {
          "rank": 2193,
          "guildName": "Faceroll",
          "displayName": "Faceroll",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4895981,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/faceroll",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/LgVtjz8T4WhyqGmn",
          "guildGroup": "ru"
        },
        {
          "rank": 2257,
          "guildName": "MUGIWARA",
          "displayName": "MUGIWARA",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4933315,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/mugiwara",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/ga8vFr7HJqN4nC3y",
          "guildGroup": "ru"
        },
        {
          "rank": 2290,
          "guildName": "Free Will",
          "displayName": "Free Will",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4956783,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/free%20will",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/2m4NMxDPGXyHv68f",
          "guildGroup": "ru"
        },
        {
          "rank": 2331,
          "guildName": "GAMBIT",
          "displayName": "GAMBIT",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4980757,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/gambit",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/jzn1taC4JLkN9Z3K",
          "guildGroup": "ru"
        },
        {
          "rank": 2389,
          "guildName": "Eternal Sleep",
          "displayName": "Eternal Sleep",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5015319,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/eternal%20sleep",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/HLBFz9gntRjWVb2h",
          "guildGroup": "ru"
        },
        {
          "rank": 3017,
          "guildName": "ATB",
          "displayName": "ATB",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5380834,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/atb",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/ypWJ2VfgHDxK9h8q",
          "guildGroup": "ua"
        },
        {
          "rank": 3173,
          "guildName": "BAPTA",
          "displayName": "BAPTA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5468789,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/bapta",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/GnvQjZTMKfc6DCyr",
          "guildGroup": "ua"
        },
        {
          "rank": 3277,
          "guildName": "Warsong",
          "displayName": "Warsong",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5580891,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/warsong",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/MNRpabD1Ft38cn7V",
          "guildGroup": "ru"
        },
        {
          "rank": 3642,
          "guildName": "MokNatal UA",
          "displayName": "MokNatal UA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5881146,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/moknatal%20ua",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/GrMpNVF78qKCf4Qk",
          "guildGroup": "ua"
        },
        {
          "rank": 3850,
          "guildName": "Ukrainian Ironbelly",
          "displayName": "Ukrainian Ironbelly",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 6043188,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/ukrainian%20ironbelly",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/wzDT1MhtKj9vbg4W",
          "guildGroup": "ua"
        },
        {
          "rank": 4630,
          "guildName": "CMEPEKA",
          "displayName": "CMEPEKA",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 7302802,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cmepeka",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/Tk2KxjcF7wPHVQYr",
          "guildGroup": "ua"
        },
        {
          "rank": 4682,
          "guildName": "Trident Reborn",
          "displayName": "Trident Reborn",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 7871517,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/trident%20reborn",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/VwAcbGgrf8XFh7aL",
          "guildGroup": "ua"
        },
        {
          "rank": null,
          "guildName": "Annuit Coeptis",
          "displayName": "Annuit Coeptis",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/annuit%20coeptis",
          "reportUrl": null,
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "CEBEP POMNIT",
          "displayName": "CEBEP POMNIT",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cebep%20pomnit",
          "reportUrl": null,
          "guildGroup": "ru"
        }
      ]
    }
  ]
};
