// AUTO-GENERATED by npm run bake:wcl-stats. Do not edit manually.

export interface WclStatsRow {
  rank: number | null;
  guildName: string;
  displayName: string;
  faction?: 'Alliance' | 'Horde' | null;
  region: string;
  realm: string;
  durationMs: number | null;
  guildUrl: string;
  reportUrl: string | null;
  guildGroup: 'milestone' | 'ua' | 'ru';
}

export interface WclStatsRaid {
  id: 'ssc' | 'tk';
  name: string;
  encounterId: number;
  rows: WclStatsRow[];
}

export interface WclStatsData { generatedAt: string; raids: WclStatsRaid[]; }

export const wclStatsData: WclStatsData = {
  "generatedAt": "2026-07-29T06:15:28.480Z",
  "raids": [
    {
      "id": "tk",
      "name": "Tempest Keep",
      "encounterId": 100703,
      "rows": [
        {
          "rank": 1,
          "guildName": "Progress",
          "displayName": "Progress",
          "faction": null,
          "region": "eu",
          "realm": "Spineshatter",
          "durationMs": 1503097,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/progress",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/1c7dHynFrhxLmtMZ",
          "guildGroup": "milestone"
        },
        {
          "rank": 50,
          "guildName": "Hopium",
          "displayName": "Hopium",
          "faction": null,
          "region": "eu",
          "realm": "Spineshatter",
          "durationMs": 2210120,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/hopium",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/W4hT6rXGCjFxJRBZ",
          "guildGroup": "milestone"
        },
        {
          "rank": 76,
          "guildName": "CBITAHOK",
          "displayName": "CBITAHOK",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2362386,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cbitahok",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/BcCFDdqfJPW1vztG",
          "guildGroup": "ua"
        },
        {
          "rank": 89,
          "guildName": "Ïzhachok",
          "displayName": "Ïzhachok",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2455610,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/%C3%AFzhachok",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/NPk1vfCW8x9Fz6RH",
          "guildGroup": "ua"
        },
        {
          "rank": 100,
          "guildName": "PP - Blue",
          "displayName": "PP - Blue",
          "faction": null,
          "region": "eu",
          "realm": "Nightslayer",
          "durationMs": 2523680,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/nightslayer/pp%20-%20blue",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/2brJHWj4fVQMp3L8",
          "guildGroup": "milestone"
        },
        {
          "rank": 109,
          "guildName": "Just Ask",
          "displayName": "Just Ask",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2556870,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/just%20ask",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/pfgz6L3WFXZcPKvR",
          "guildGroup": "ru"
        },
        {
          "rank": 231,
          "guildName": "BOARS",
          "displayName": "BOARS",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2883583,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/boars",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/raL7xYdbwnpZKkjq",
          "guildGroup": "ru"
        },
        {
          "rank": 245,
          "guildName": "DELETED",
          "displayName": "DELETED",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2900918,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/deleted",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/PdGzx43D6R29LWBt",
          "guildGroup": "ru"
        },
        {
          "rank": 279,
          "guildName": "Dwarves drank Baikal",
          "displayName": "Dwarves drank Baikal",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2967576,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/dwarves%20drank%20baikal",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/qBRcV2PhD4FQw8Ty",
          "guildGroup": "ru"
        },
        {
          "rank": 752,
          "guildName": "Unexpected Journey",
          "displayName": "Unexpected Journey",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3394936,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/unexpected%20journey",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/q74vxfXF8P3LGApC",
          "guildGroup": "ru"
        },
        {
          "rank": 827,
          "guildName": "N O R D",
          "displayName": "N O R D",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3441239,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/n%20o%20r%20d",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/LkyMdaJ6hH7Cbt4W",
          "guildGroup": "ru"
        },
        {
          "rank": 942,
          "guildName": "Its Official",
          "displayName": "Its Official",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3503663,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/its%20official",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/Y68aGcwrBWmkbqQ3",
          "guildGroup": "ru"
        },
        {
          "rank": 960,
          "guildName": "Trade Goods",
          "displayName": "Trade Goods",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3514056,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/trade%20goods",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/j9JqVD3wRmnCkgtT",
          "guildGroup": "ru"
        },
        {
          "rank": 1193,
          "guildName": "SWP in Three Days",
          "displayName": "SWP in Three Days",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3636166,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/swp%20in%20three%20days",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/FPQzN9xfC4c6hAG8",
          "guildGroup": "ua"
        },
        {
          "rank": 1216,
          "guildName": "Eternal Sleep",
          "displayName": "Eternal Sleep",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3648529,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/eternal%20sleep",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/Wpcwjdz3trNnMC6T",
          "guildGroup": "ru"
        },
        {
          "rank": 1394,
          "guildName": "GAMBIT",
          "displayName": "GAMBIT",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3725566,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/gambit",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/jzn1taC4JLkN9Z3K",
          "guildGroup": "ru"
        },
        {
          "rank": 1894,
          "guildName": "MATRëSHKA",
          "displayName": "MATRëSHKA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3918245,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/matr%C3%ABshka",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/7TGajDwV6zvgnxfc",
          "guildGroup": "ru"
        },
        {
          "rank": 2202,
          "guildName": "LiberalPug",
          "displayName": "LiberalPug",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4023609,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/liberalpug",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/MKw6bAjP9FXYVgkh",
          "guildGroup": "ua"
        },
        {
          "rank": 2374,
          "guildName": "MokNatal UA",
          "displayName": "MokNatal UA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4091681,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/moknatal%20ua",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/zJHTymvwj8BQpcV4",
          "guildGroup": "ua"
        },
        {
          "rank": 2400,
          "guildName": "ATB",
          "displayName": "ATB",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4104524,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/atb",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/RQr1gdYLFqWHVnBJ",
          "guildGroup": "ua"
        },
        {
          "rank": 2929,
          "guildName": "Faceroll",
          "displayName": "Faceroll",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4341209,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/faceroll",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/LgVtjz8T4WhyqGmn",
          "guildGroup": "ru"
        },
        {
          "rank": 3089,
          "guildName": "MUGIWARA",
          "displayName": "MUGIWARA",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4405630,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/mugiwara",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/JTNrA2PcMRkLYj36",
          "guildGroup": "ru"
        },
        {
          "rank": 3142,
          "guildName": "Free Will",
          "displayName": "Free Will",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4434071,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/free%20will",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/ZAYBDMdfGXjW4L32",
          "guildGroup": "ru"
        },
        {
          "rank": 3302,
          "guildName": "Warsong",
          "displayName": "Warsong",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4514287,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/warsong",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/HD2FYmq83kPAagp6",
          "guildGroup": "ru"
        },
        {
          "rank": 3409,
          "guildName": "BAPTA",
          "displayName": "BAPTA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4593944,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/bapta",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/rQBtG4XpnLMTc8K3",
          "guildGroup": "ua"
        },
        {
          "rank": 3728,
          "guildName": "Ukrainian Ironbelly",
          "displayName": "Ukrainian Ironbelly",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4772495,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/ukrainian%20ironbelly",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/HL6F9GAPTXj7wM4m",
          "guildGroup": "ua"
        },
        {
          "rank": 4155,
          "guildName": "CMEPEKA",
          "displayName": "CMEPEKA",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5080346,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cmepeka",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/b1Gt4n8gaY9TXAxR",
          "guildGroup": "ua"
        },
        {
          "rank": 4794,
          "guildName": "Trident Reborn",
          "displayName": "Trident Reborn",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 6365911,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/trident%20reborn",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/qAYmLQbwM4GKZx9j",
          "guildGroup": "ua"
        },
        {
          "rank": 4794,
          "guildName": "CEBEP POMNIT",
          "displayName": "CEBEP POMNIT",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 11606605,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cebep%20pomnit",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/8dJPLYw36mFkHtrb",
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "Annuit Coeptis",
          "displayName": "Annuit Coeptis",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/annuit%20coeptis",
          "reportUrl": null,
          "guildGroup": "ru"
        }
      ]
    },
    {
      "id": "ssc",
      "name": "Serpentshrine Cavern",
      "encounterId": 100702,
      "rows": [
        {
          "rank": 1,
          "guildName": "Progress",
          "displayName": "Progress",
          "faction": null,
          "region": "eu",
          "realm": "Spineshatter",
          "durationMs": 1563192,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/progress",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/dRw6AyZGWNVCJH9j",
          "guildGroup": "milestone"
        },
        {
          "rank": 50,
          "guildName": "muppets OCE",
          "displayName": "muppets OCE",
          "faction": null,
          "region": "eu",
          "realm": "Nightslayer",
          "durationMs": 2349114,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/nightslayer/muppets%20oce",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/my8kDq1PZfXad6jt",
          "guildGroup": "milestone"
        },
        {
          "rank": 79,
          "guildName": "Ïzhachok",
          "displayName": "Ïzhachok",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2536632,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/%C3%AFzhachok",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/rMRVDtqC3kc7Wa8G",
          "guildGroup": "ua"
        },
        {
          "rank": 82,
          "guildName": "Just Ask",
          "displayName": "Just Ask",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2554636,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/just%20ask",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/pfgz6L3WFXZcPKvR",
          "guildGroup": "ru"
        },
        {
          "rank": 96,
          "guildName": "CBITAHOK",
          "displayName": "CBITAHOK",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 2661168,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cbitahok",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/7XF4TNfpdYywHCRz",
          "guildGroup": "ua"
        },
        {
          "rank": 100,
          "guildName": "Vision",
          "displayName": "Vision",
          "faction": null,
          "region": "eu",
          "realm": "Nightslayer",
          "durationMs": 2677726,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/nightslayer/vision",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/1d7pkNLKqPwY4nRV",
          "guildGroup": "milestone"
        },
        {
          "rank": 167,
          "guildName": "Dwarves drank Baikal",
          "displayName": "Dwarves drank Baikal",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3058749,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/dwarves%20drank%20baikal",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/hXDGJkxCpWrdQK1Y",
          "guildGroup": "ru"
        },
        {
          "rank": 188,
          "guildName": "BOARS",
          "displayName": "BOARS",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3146415,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/boars",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/w9TaZgxDykfmJ6dN",
          "guildGroup": "ru"
        },
        {
          "rank": 244,
          "guildName": "DELETED",
          "displayName": "DELETED",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3308713,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/deleted",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/AGCzmPtaJXw6MRTK",
          "guildGroup": "ru"
        },
        {
          "rank": 435,
          "guildName": "N O R D",
          "displayName": "N O R D",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3654884,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/n%20o%20r%20d",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/z31gpbWZvtNy2RqJ",
          "guildGroup": "ru"
        },
        {
          "rank": 551,
          "guildName": "Unexpected Journey",
          "displayName": "Unexpected Journey",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3774512,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/unexpected%20journey",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/ZGkHtgnTdJKymN8r",
          "guildGroup": "ru"
        },
        {
          "rank": 623,
          "guildName": "SWP in Three Days",
          "displayName": "SWP in Three Days",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3851015,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/swp%20in%20three%20days",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/AY7GHgh4Fk8NvtD9",
          "guildGroup": "ua"
        },
        {
          "rank": 680,
          "guildName": "Trade Goods",
          "displayName": "Trade Goods",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 3899692,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/trade%20goods",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/4PmDTBcnArygpCX7",
          "guildGroup": "ru"
        },
        {
          "rank": 1247,
          "guildName": "Its Official",
          "displayName": "Its Official",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4319260,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/its%20official",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/Y68aGcwrBWmkbqQ3",
          "guildGroup": "ru"
        },
        {
          "rank": 1756,
          "guildName": "MATRëSHKA",
          "displayName": "MATRëSHKA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4583444,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/matr%C3%ABshka",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/wHcVPAm1xF7jRZTD",
          "guildGroup": "ru"
        },
        {
          "rank": 1795,
          "guildName": "GAMBIT",
          "displayName": "GAMBIT",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4602151,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/gambit",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/ja28ZmBAbD3PKJnx",
          "guildGroup": "ru"
        },
        {
          "rank": 2245,
          "guildName": "LiberalPug",
          "displayName": "LiberalPug",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4808705,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/liberalpug",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/MKw6bAjP9FXYVgkh",
          "guildGroup": "ua"
        },
        {
          "rank": 2401,
          "guildName": "Faceroll",
          "displayName": "Faceroll",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4895981,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/faceroll",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/LgVtjz8T4WhyqGmn",
          "guildGroup": "ru"
        },
        {
          "rank": 2471,
          "guildName": "MUGIWARA",
          "displayName": "MUGIWARA",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4933315,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/mugiwara",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/ga8vFr7HJqN4nC3y",
          "guildGroup": "ru"
        },
        {
          "rank": 2497,
          "guildName": "Free Will",
          "displayName": "Free Will",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 4956783,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/free%20will",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/2m4NMxDPGXyHv68f",
          "guildGroup": "ru"
        },
        {
          "rank": 2603,
          "guildName": "Eternal Sleep",
          "displayName": "Eternal Sleep",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5015319,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/eternal%20sleep",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/HLBFz9gntRjWVb2h",
          "guildGroup": "ru"
        },
        {
          "rank": 2975,
          "guildName": "MokNatal UA",
          "displayName": "MokNatal UA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5247987,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/moknatal%20ua",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/zJHTymvwj8BQpcV4",
          "guildGroup": "ua"
        },
        {
          "rank": 3187,
          "guildName": "ATB",
          "displayName": "ATB",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5360898,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/atb",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/VNGC2yctKZad6FAP",
          "guildGroup": "ua"
        },
        {
          "rank": 3347,
          "guildName": "BAPTA",
          "displayName": "BAPTA",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5468789,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/bapta",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/GnvQjZTMKfc6DCyr",
          "guildGroup": "ua"
        },
        {
          "rank": 3400,
          "guildName": "Ukrainian Ironbelly",
          "displayName": "Ukrainian Ironbelly",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5516700,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/ukrainian%20ironbelly",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/6vpG98PWyYwad2B1",
          "guildGroup": "ua"
        },
        {
          "rank": 3453,
          "guildName": "Trident Reborn",
          "displayName": "Trident Reborn",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5560230,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/trident%20reborn",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/WZYT6mN4L2vrMGyD",
          "guildGroup": "ua"
        },
        {
          "rank": 3453,
          "guildName": "Warsong",
          "displayName": "Warsong",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 5580891,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/warsong",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/MNRpabD1Ft38cn7V",
          "guildGroup": "ru"
        },
        {
          "rank": 4781,
          "guildName": "CMEPEKA",
          "displayName": "CMEPEKA",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": 7302802,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cmepeka",
          "reportUrl": "https://fresh.warcraftlogs.com/reports/Tk2KxjcF7wPHVQYr",
          "guildGroup": "ua"
        },
        {
          "rank": null,
          "guildName": "Annuit Coeptis",
          "displayName": "Annuit Coeptis",
          "faction": "Alliance",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/annuit%20coeptis",
          "reportUrl": null,
          "guildGroup": "ru"
        },
        {
          "rank": null,
          "guildName": "CEBEP POMNIT",
          "displayName": "CEBEP POMNIT",
          "faction": "Horde",
          "region": "eu",
          "realm": "spineshatter",
          "durationMs": null,
          "guildUrl": "https://fresh.warcraftlogs.com/guild/eu/spineshatter/cebep%20pomnit",
          "reportUrl": null,
          "guildGroup": "ru"
        }
      ]
    }
  ]
};
